#!/bin/bash

# Create video from frames generated by shapeme or shapeme-ga

FRAMERATE=${1:-30}
OUTPUT=${2:-evolution.mp4}
CRF=${3:-18}

if [ ! -d "frames" ] || [ -z "$(ls -A frames 2>/dev/null)" ]; then
    echo "Error: frames/ directory is empty or does not exist"
    echo "Run shapeme or shapeme-ga first to generate frames"
    exit 1
fi

echo "Creating video: $OUTPUT (framerate=$FRAMERATE, crf=$CRF)"

ffmpeg -y -framerate "$FRAMERATE" -i frames/frame_%06d.png \
    -c:v libx264 -crf "$CRF" -pix_fmt yuv420p "$OUTPUT"

echo "Done: $OUTPUT"
